### ISSUE TITLE
Milestone 2 tasks

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-ruby#3]
In this milestone, we focus on cleaning up existing code and make it ready for OpenSearch development 

- [x]  Remove X-Pack and non oss features/tests and commits not related to >7.10 from *main* branch
- [x]  remove x-elastic meta header
- [x] Update CI to run with  Opendistro docker image without security plugin (all tests should pass)
- [x] Delete docs, examples ( any *. asciidoc that are added from fork repository)
